# Generated by Django 3.2.6 on 2021-12-29 08:42

import django.core.validators
from django.db import migrations, models
import internationalflavor.vat_number.models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationIndividual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('SIG.RA', 'SIG.RA'), ('GEOM.', 'GEOM.'), ('RAG.', 'RAG.'), ('ING.', 'ING.'), ('ARCH', 'ARCH'), ('ALTRO', 'ALTRO')], max_length=50, verbose_name='TITOLO AMMINISTRATORE')),
                ('name', models.CharField(max_length=120, verbose_name='COGNOME e NOME')),
                ('fiscal_code', models.CharField(blank=True, max_length=16, verbose_name='CODICE FISCALE')),
                ('vat_number', internationalflavor.vat_number.models.VATNumberField(blank=True, countries=['IT'], verbose_name='PARTITA IVA')),
                ('dob', models.DateField(blank=True, verbose_name='DATA DI NASCITA')),
                ('birthplace', models.CharField(blank=True, max_length=50, verbose_name='COMUNE DI NASCITA')),
                ('birthplace_county', models.CharField(blank=True, max_length=30, verbose_name='PROVINCIA DI NASCITA')),
                ('activity_street', models.CharField(blank=True, max_length=50, verbose_name="VIA E NUMERO/I SEDE ATTIVITA'")),
                ('activity_location_cap', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name="CAP SEDE ATTIVITA'")),
                ('activity_municipality', models.CharField(blank=True, max_length=50, verbose_name="COMUNE SEDE ATTIVITA'")),
                ('activity_province', models.CharField(blank=True, max_length=50, verbose_name="PROVINCIA SEDE ATTIVITA'")),
                ('residence_street', models.CharField(blank=True, max_length=50, verbose_name='VIA E NUMERO RESIDENZA')),
                ('residence_cap', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name='CAP RESIDENZA')),
                ('residence_city', models.CharField(blank=True, max_length=50, verbose_name='COMUNE DI RESIDENZA')),
                ('residence_province', models.CharField(blank=True, max_length=50, verbose_name='PROVINCIA DI RESIDENZA')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdministrationLegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, verbose_name="DENOMINAZIONE SOCIETA'")),
                ('province', models.CharField(blank=True, max_length=20, verbose_name='PROVINCIA/E ISCRIZIONE')),
                ('company_register', models.BigIntegerField(blank=True, verbose_name='REGISTRO IMPRESE')),
                ('vat_number', internationalflavor.vat_number.models.VATNumberField(blank=True, countries=['IT'], verbose_name='N° ISCRIZIONE REGISTRO IMPRESE - PARTITA IVA - C.F.')),
                ('street_legal', models.CharField(blank=True, max_length=100, verbose_name='VIA E NUMERO SEDE LEGALE')),
                ('cap_legal', models.CharField(blank=True, max_length=30, verbose_name='CAP SEDE LEGALE')),
                ('municipal_reg_office', models.CharField(blank=True, max_length=30, verbose_name='COMUNE SEDE LEGALE')),
                ('province_reg_office', models.CharField(blank=True, max_length=20, verbose_name='PROVINCIA SEDE LEGALE')),
                ('legal_title_rep', models.CharField(choices=[('SIG.RA', 'SIG.RA'), ('GEOM.', 'GEOM.'), ('RAG.', 'RAG.'), ('ING.', 'ING.'), ('ARCH', 'ARCH'), ('ALTRO', 'ALTRO')], max_length=10, null=True, verbose_name='TITOLO LEGALE RAPPRESENTATE')),
                ('leg_rep_name', models.CharField(blank=True, max_length=100, verbose_name='COGNOME E NOME LEGALE RAPPRESENTANTE')),
                ('leg_rep_tax_code', models.CharField(blank=True, max_length=20, verbose_name='CODICE FISCALE LEGALE RAPPRESENTATE')),
                ('leg_rep_dob', models.DateField(blank=True, verbose_name='DATA DI NASCITA LEGALE RAPPRESENTANTE')),
                ('municipal_of_birth_of_leg', models.CharField(blank=True, max_length=30, verbose_name='COMUNE DI NASCITA DEL LEGALE RAPPRESENTANTE')),
                ('province_of_birth_of_leg', models.CharField(blank=True, max_length=30, verbose_name='PROVINCIA DI NASCITA DEL LEGALE RAPPRESENTANTE')),
                ('leg_rep_street', models.CharField(blank=True, max_length=50, verbose_name='VIA E NUMERO RESIDENZA LEGALE RAPPRESENTANTE')),
                ('cap_rep_res', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)], verbose_name='CAP RESIDENZA LEGALE RAPPRESENTANTE')),
                ('municipal_of_leg_residence', models.CharField(blank=True, max_length=30, verbose_name='COMUNE DI RESIDENZA LEGALE RAPPRESENTANTE')),
                ('province_of_leg_residence', models.CharField(blank=True, max_length=30, verbose_name='PROVINCIA DI RESIDENZA LEGALE RAPPRESENTANTE')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
