# Generated by Django 3.2.6 on 2022-04-06 13:48

import apps.superbonus.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.superbonus.models.validate_fiscal_code], verbose_name='CODICE FISCALE'),
        ),
        migrations.AlterField(
            model_name='administrationlegal',
            name='leg_rep_tax_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.superbonus.models.validate_fiscal_code], verbose_name='CODICE FISCALE LEGALE RAPPRESENTATE'),
        ),
        migrations.AlterField(
            model_name='bonuscondo',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.superbonus.models.validate_fiscal_code], verbose_name='CODICE FISCALE'),
        ),
        migrations.AlterField(
            model_name='bonusvilla',
            name='email',
            field=models.EmailField(max_length=254, verbose_name="INDIRIZZO MAIL DELL'IMMOBILE - DEL CLIENTE"),
        ),
        migrations.AlterField(
            model_name='bonusvilla',
            name='pec_mail',
            field=models.EmailField(max_length=254, verbose_name="INDIRIZZO PEC DELL'IMMOBILE - DEL CLIENTE"),
        ),
        migrations.AlterField(
            model_name='catastaldata',
            name='n_catastal_cheet',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='N° FOGLIO CATASTALE DI APPARTENENZA'),
        ),
        migrations.AlterField(
            model_name='catastaldata',
            name='n_first_particle',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='N° PRIMA PARTICELLA COSTITUENTE IL CONDOMINIO'),
        ),
    ]
