# Generated by Django 3.2.6 on 2022-04-07 13:46

import apps.superbonus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0002_auto_20220406_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catastaldata',
            name='n_catastal_cheet',
            field=models.IntegerField(validators=[apps.superbonus.models.positive_num_validator], verbose_name='N° FOGLIO CATASTALE DI APPARTENENZA'),
        ),
        migrations.AlterField(
            model_name='catastaldata',
            name='n_fifth_particle',
            field=models.IntegerField(blank=True, null=True, validators=[apps.superbonus.models.positive_num_validator], verbose_name='N° QUINTA PARTICELLA COSTITUENTE IL CONDOMINIO'),
        ),
        migrations.AlterField(
            model_name='catastaldata',
            name='n_first_particle',
            field=models.IntegerField(validators=[apps.superbonus.models.positive_num_validator], verbose_name='N° PRIMA PARTICELLA COSTITUENTE IL CONDOMINIO'),
        ),
        migrations.AlterField(
            model_name='catastaldata',
            name='n_fourth_particle',
            field=models.IntegerField(blank=True, null=True, validators=[apps.superbonus.models.positive_num_validator], verbose_name='N° QUARTA PARTICELLA COSTITUENTE IL CONDOMINIO'),
        ),
        migrations.AlterField(
            model_name='catastaldata',
            name='n_second_particle',
            field=models.IntegerField(blank=True, null=True, validators=[apps.superbonus.models.positive_num_validator], verbose_name='N° SECONDA PARTICELLA COSTITUENTE IL CONDOMINIO'),
        ),
        migrations.AlterField(
            model_name='catastaldata',
            name='n_third_particle',
            field=models.IntegerField(blank=True, null=True, validators=[apps.superbonus.models.positive_num_validator], verbose_name='N° TERZA PARTICELLA COSTITUENTE IL CONDOMINIO'),
        ),
    ]
