# Generated by Django 3.2.6 on 2021-12-30 12:39

import apps.superbonus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0003_auto_20211229_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.superbonus.models.validate_cap], verbose_name='CAP RESIDENZA'),
        ),
        migrations.AlterField(
            model_name='bonuscondo',
            name='common_location',
            field=models.CharField(blank=True, max_length=50, verbose_name='COMUNE UBICAZIONE CONDOMINIO - IMMOBILE'),
        ),
    ]
