# Generated by Django 3.2.6 on 2021-12-30 13:05

import apps.superbonus.models
import datetime
from django.db import migrations, models
import internationalflavor.vat_number.models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0004_auto_20211230_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationindividual',
            name='activity_location_cap',
            field=models.CharField(max_length=5, validators=[apps.superbonus.models.validate_cap], verbose_name="CAP SEDE ATTIVITA'"),
        ),
        migrations.AlterField(
            model_name='administrationindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='DATA DI NASCITA'),
        ),
        migrations.AlterField(
            model_name='administrationindividual',
            name='vat_number',
            field=internationalflavor.vat_number.models.VATNumberField(countries=['IT'], default='IT12345678901', verbose_name='PARTITA IVA'),
        ),
        migrations.AlterField(
            model_name='administrationlegal',
            name='cap_legal',
            field=models.CharField(max_length=5, validators=[apps.superbonus.models.validate_cap], verbose_name='CAP SEDE LEGALE'),
        ),
        migrations.AlterField(
            model_name='administrationlegal',
            name='cap_rep_res',
            field=models.CharField(max_length=5, validators=[apps.superbonus.models.validate_cap], verbose_name='CAP RESIDENZA LEGALE RAPPRESENTANTE'),
        ),
        migrations.AlterField(
            model_name='administrationlegal',
            name='leg_rep_dob',
            field=models.DateField(default=datetime.date.today, verbose_name='DATA DI NASCITA LEGALE RAPPRESENTANTE'),
        ),
        migrations.AlterField(
            model_name='administrationlegal',
            name='vat_number',
            field=internationalflavor.vat_number.models.VATNumberField(countries=['IT'], default='IT12345678901', verbose_name='N° ISCRIZIONE REGISTRO IMPRESE - PARTITA IVA - C.F.'),
        ),
        migrations.AlterField(
            model_name='bonuscondo',
            name='cap',
            field=models.CharField(max_length=5, validators=[apps.superbonus.models.validate_cap], verbose_name='CAP UBICAZIONE CONDOMINIO - IMMOBILE'),
        ),
        migrations.AlterField(
            model_name='bonusvilla',
            name='cap',
            field=models.CharField(max_length=5, validators=[apps.superbonus.models.validate_cap], verbose_name="CAP UBICAZIONE DELL'IMMOBILE"),
        ),
        migrations.AlterField(
            model_name='interventions',
            name='date_of_assembly',
            field=models.DateField(default=datetime.date.today, verbose_name='DATA ASSEMBLEA CONDOMINIALE IN CUI I CONDOMINI HANNO IRREVOCABILMENTE OPTATO PER LO SCONTO IN FATTURA'),
        ),
    ]
