# Generated by Django 3.2.6 on 2022-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0003_alter_beneficiary_single_ownership_fee'),
        ('superbonus', '0005_auto_20211230_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuscondo',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='bonuscondo',
            name='beneficiary',
            field=models.ManyToManyField(to='beneficary.Beneficiary', verbose_name='DETTAGLIO DEI BENEFICIARI'),
        ),
    ]
