# Generated by Django 3.2.6 on 2022-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0003_alter_beneficiary_single_ownership_fee'),
        ('superbonus', '0006_auto_20220104_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusvilla',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='bonusvilla',
            name='beneficiary',
            field=models.ManyToManyField(to='beneficary.Beneficiary', verbose_name='DETTAGLIO DEI BENEFICIARI'),
        ),
    ]
