# Generated by Django 3.2.6 on 2022-01-28 11:57

import apps.superbonus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0007_auto_20220112_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusVillaFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('files', models.FileField(upload_to='BonusVilla/file/%Y/%m/%d/', validators=[apps.superbonus.models.validate_file_extension])),
                ('images', models.ImageField(upload_to='BonusVilla/image/%Y/%m/%d/')),
            ],
        ),
    ]
