# Generated by Django 3.2.6 on 2022-01-28 13:17

import apps.superbonus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0008_bonusvillafiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusvillafiles',
            name='files',
            field=models.FileField(upload_to='BonusVilla/file/', validators=[apps.superbonus.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='bonusvillafiles',
            name='images',
            field=models.ImageField(upload_to='BonusVilla/image/'),
        ),
    ]
