# Generated by Django 3.2.6 on 2022-01-28 13:19

import apps.superbonus.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0009_auto_20220128_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusvillafiles',
            name='villa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superbonus.bonusvilla'),
        ),
        migrations.AlterField(
            model_name='bonusvillafiles',
            name='files',
            field=models.FileField(blank=True, upload_to='BonusVilla/file/', validators=[apps.superbonus.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='bonusvillafiles',
            name='images',
            field=models.ImageField(blank=True, upload_to='BonusVilla/image/'),
        ),
    ]
