# Generated by Django 3.2.6 on 2022-02-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0010_auto_20220128_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusvillafiles',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
