# Generated by Django 3.2.6 on 2022-02-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0015_alter_bonusvillafiles_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UPLOADED', 'CARICATO'), ('VERIFIED', 'VERIFICATO'), ('AUTHORISED', 'AUTORIZZATO')], max_length=15)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superbonus.bank', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileRequired',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('file1', models.FileField(blank=True, upload_to='')),
                ('file2', models.FileField(blank=True, upload_to='')),
                ('supoerbonus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superbonus.superbonus')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bonusvilla',
            options={},
        ),
        migrations.DeleteModel(
            name='BonusVillaFiles',
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superbonus.filerequired', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='bankrequirements',
            unique_together={('bank_id', 'file_id')},
        ),
    ]
