# Generated by Django 3.2.6 on 2022-02-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0016_auto_20220218_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrequirements',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superbonus.bank'),
        ),
        migrations.AlterField(
            model_name='bankrequirements',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superbonus.filerequired'),
        ),
    ]
