# Generated by Django 3.2.6 on 2022-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0017_auto_20220218_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrequirements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='bankrequirements',
            unique_together={('bank_id', 'file_id', 'id')},
        ),
    ]
