# Generated by Django 3.2.6 on 2022-02-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0018_auto_20220218_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filerequired',
            old_name='supoerbonus_id',
            new_name='superbonus_id',
        ),
        migrations.AddField(
            model_name='bonuscondo',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superbonus.bank', verbose_name='DOMANDA BANCARIA'),
        ),
        migrations.AddField(
            model_name='bonusvilla',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superbonus.bank', verbose_name='DOMANDA BANCARIA'),
        ),
    ]
