# Generated by Django 3.2.6 on 2022-02-21 15:51

import apps.superbonus.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0019_auto_20220221_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusFile',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='superbonus.filerequired')),
                ('status', models.CharField(choices=[('UPLOADED', 'CARICATO'), ('VERIFIED', 'VERIFICATO'), ('AUTHORISED', 'AUTORIZZATO')], default='UPLOADED', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='filerequired',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='filerequired',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='filerequired',
            name='superbonus_id',
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='admin_hi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahi', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aid', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cat_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catp', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cond_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creg', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cond_registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cregi', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cond_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctax', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='thousand_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tt', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='filerequired',
            name='file',
            field=models.FileField(null=True, upload_to=apps.superbonus.models.user_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='bankrequirements',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bankrequirements',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='bankrequirements',
            name='status',
        ),
    ]
