# Generated by Django 3.2.6 on 2022-02-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0020_auto_20220221_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrequirements',
            name='bonus',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='superbonus.superbonus'),
            preserve_default=False,
        ),
    ]
