# Generated by Django 3.2.6 on 2022-02-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0021_bankrequirements_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrequirements',
            name='bank_id',
        ),
    ]
