# Generated by Django 3.2.6 on 2022-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0022_remove_bankrequirements_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequired',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
