# Generated by Django 3.2.6 on 2022-02-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0024_alter_filerequired_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequired',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
