# Generated by Django 3.2.6 on 2022-02-22 12:20

import apps.superbonus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0025_alter_filerequired_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerequired',
            name='file',
            field=models.FileField(upload_to=apps.superbonus.models.user_directory_path),
        ),
    ]
