# Generated by Django 3.2.6 on 2022-02-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0026_alter_filerequired_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superbonus',
            options={},
        ),
        migrations.AlterField(
            model_name='bankrequirements',
            name='admin_id',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.CASCADE, related_name='aid', to='superbonus.filerequired'),
            preserve_default=False,
        ),
    ]
