# Generated by Django 3.2.6 on 2022-02-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0027_auto_20220222_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrequirements',
            name='any_binding_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abdocs', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='ape_ante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aa', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='app_of_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_addmin', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assi', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cert_enroll_qto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceqto', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cert_of_reg_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coro', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cert_poss_real_right_enjoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cprre', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cons_for_exe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfeow', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='construction_site_sc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cssc', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='contract_cert_cor_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cccr', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='contract_cert_corr_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cccreg', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='copy_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_invoice', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='dec_of_con_by_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docbto', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='dec_of_con_of_exis_sys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docoes', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='dec_of_cons_spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_spouse', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='dec_of_enroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doer', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='declar_of_cons_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docbo', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='declaration_con_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcbo', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='declaration_of_cons_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docbo_l', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='deed_of_owner_purch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doop', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='doc_cert_fairness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcfoi', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='estate_unit_cat_visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reucv', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='hic_condo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hic', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='id_card_condo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_condo', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='lat_building_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lbt', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='leg_status_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lsos', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='leg_title_proc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ltp', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='liability_insurance_asseverate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_ins_ass', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='metric_cal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mc', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='notary_act_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_act', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='notary_act_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_act_b', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='pre_cont_reg_place_in_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcrpip', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='pre_contract_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcrpp', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='presumed_deadline_sal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pds', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='proc_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcontract', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='prof_of_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pop', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='res_of_cond_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rocms', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='sowc_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sowcnot', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='sowc_practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sowcp', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='sub_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contract', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='t_of_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_spouse', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='tax_pre_feas_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpfs', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='tech_pre_feas_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpvs', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='tech_prot_ad_ver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpfav', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='title_of_possession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='towed_inter_comp_cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticcco', to='superbonus.filerequired'),
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='visura_aurica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vis_auri', to='superbonus.filerequired'),
        ),
    ]
