# Generated by Django 3.2.6 on 2022-03-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0028_auto_20220228_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrequirements',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aid', to='superbonus.filerequired'),
        ),
        migrations.AlterField(
            model_name='bonuscondo',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superbonus.bank', verbose_name='ISTITUTO DI CREDITO'),
        ),
        migrations.AlterField(
            model_name='bonusvilla',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superbonus.bank', verbose_name='ISTITUTO DI CREDITO'),
        ),
    ]
