# Generated by Django 3.2.6 on 2022-03-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0029_auto_20220301_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrequirements',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid', to='superbonus.filerequired'),
        ),
    ]
