# Generated by Django 3.2.6 on 2022-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0031_auto_20220301_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrequirements',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='admin_id',
            field=models.ManyToManyField(to='superbonus.FileRequired'),
        ),
    ]
