# Generated by Django 3.2.6 on 2022-03-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbonus', '0032_auto_20220301_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrequirements',
            name='admin_hi',
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='admin_hi',
            field=models.ManyToManyField(related_name='ahi', to='superbonus.FileRequired'),
        ),
        migrations.AlterField(
            model_name='bankrequirements',
            name='admin_id',
            field=models.ManyToManyField(related_name='aid', to='superbonus.FileRequired'),
        ),
        migrations.RemoveField(
            model_name='bankrequirements',
            name='cond_reg',
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cond_reg',
            field=models.ManyToManyField(related_name='creg', to='superbonus.FileRequired'),
        ),
        migrations.RemoveField(
            model_name='bankrequirements',
            name='cond_tax',
        ),
        migrations.AddField(
            model_name='bankrequirements',
            name='cond_tax',
            field=models.ManyToManyField(related_name='ctax', to='superbonus.FileRequired'),
        ),
    ]
