# Generated by Django 3.2.6 on 2021-11-09 09:31

from django.db import migrations, models
import django.db.models.deletion
import internationalflavor.vat_number.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDesignerIndividual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('birthplace', models.CharField(max_length=30)),
                ('birthplace_county', models.CharField(max_length=30)),
                ('residence_street', models.CharField(max_length=50)),
                ('residence_cap', models.IntegerField()),
                ('residence_city', models.CharField(max_length=50)),
                ('residence_province', models.CharField(max_length=50)),
                ('activity_street', models.CharField(max_length=50)),
                ('activity_cap', models.IntegerField()),
                ('activity_municipality', models.CharField(max_length=50)),
                ('activity_province', models.CharField(max_length=50)),
                ('province_head_office', models.CharField(max_length=50)),
                ('cap_headquarters', models.CharField(max_length=50)),
                ('board_order_registration', models.CharField(max_length=50)),
                ('province_college', models.CharField(max_length=40)),
                ('number_description', models.IntegerField()),
                ('vat_number', internationalflavor.vat_number.models.VATNumberField(countries=['IT', 'NL'])),
                ('fiscal_code', models.IntegerField()),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('security_case_technician', models.IntegerField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formfaccata')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataDesignerLegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('municipal_reg_office', models.CharField(max_length=20)),
                ('province_reg_office', models.CharField(max_length=20)),
                ('cap_reg_office', models.CharField(max_length=20)),
                ('street_reg_office', models.CharField(max_length=100)),
                ('province_of_inscription_enterprises_register', models.CharField(max_length=20)),
                ('number_of_inscription_enterprises_register', internationalflavor.vat_number.models.VATNumberField(countries=['IT', 'NL'])),
                ('rep_name', models.CharField(max_length=100)),
                ('rep_dob', models.DateField()),
                ('rep_dob_municipality', models.CharField(max_length=50)),
                ('rep_dob_province', models.CharField(max_length=50)),
                ('rep_residence_zip', models.CharField(max_length=30)),
                ('rep_street', models.CharField(max_length=100)),
                ('rep_residence_municipality', models.CharField(max_length=100)),
                ('rep_fiscal_code', models.CharField(max_length=20)),
                ('rep_phone_number', models.IntegerField()),
                ('ss_fund', models.IntegerField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formfaccata')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DataDirectorWorksIndividual',
            fields=[
                ('datadesignerindividual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerindividual')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerindividual',),
        ),
        migrations.CreateModel(
            name='DataDirectorWorksLegal',
            fields=[
                ('datadesignerlegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerlegal')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerlegal',),
        ),
        migrations.CreateModel(
            name='DataEnergyExpertIndividual',
            fields=[
                ('datadesignerindividual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerindividual')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerindividual',),
        ),
        migrations.CreateModel(
            name='DataEnergyExpertLegal',
            fields=[
                ('datadesignerlegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerlegal')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerlegal',),
        ),
        migrations.CreateModel(
            name='DataResponsibleForWorksIndividual',
            fields=[
                ('datadesignerindividual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerindividual')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerindividual',),
        ),
        migrations.CreateModel(
            name='DataResponsibleForWorksLegal',
            fields=[
                ('datadesignerlegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerlegal')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerlegal',),
        ),
        migrations.CreateModel(
            name='DataSecurityCoordinatorExecutionIndividual',
            fields=[
                ('datadesignerindividual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerindividual')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerindividual',),
        ),
        migrations.CreateModel(
            name='DataSecurityCoordinatorExecutionLegal',
            fields=[
                ('datadesignerlegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerlegal')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerlegal',),
        ),
        migrations.CreateModel(
            name='DataSecurityCoordinatorIndividual',
            fields=[
                ('datadesignerindividual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerindividual')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerindividual',),
        ),
        migrations.CreateModel(
            name='DataSecurityCoordinatorLegal',
            fields=[
                ('datadesignerlegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerlegal')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerlegal',),
        ),
        migrations.CreateModel(
            name='DataThermoTechnicalIndividual',
            fields=[
                ('datadesignerindividual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerindividual')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerindividual',),
        ),
        migrations.CreateModel(
            name='DataThermoTechnicalLegal',
            fields=[
                ('datadesignerlegal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='professionals.datadesignerlegal')),
            ],
            options={
                'managed': True,
            },
            bases=('professionals.datadesignerlegal',),
        ),
    ]
