# Generated by Django 3.2.6 on 2022-04-07 13:46

import apps.professionals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadesignerindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datadesignerlegal',
            name='rep_fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datadirectorworksindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datadirectorworkslegal',
            name='rep_fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertlegal',
            name='rep_fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworksindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworkslegal',
            name='rep_fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionlegal',
            name='rep_fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorlegal',
            name='rep_fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datathermotechnicalindividual',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
        migrations.AlterField(
            model_name='datathermotechnicallegal',
            name='rep_fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[apps.professionals.models.validate_fiscal_code]),
        ),
    ]
