# Generated by Django 3.2.6 on 2021-11-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadesignerindividual',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='datadesignerlegal',
            name='form_id',
        ),
        migrations.CreateModel(
            name='Prof_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designer_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disgner_individual', to='professionals.datadesignerindividual')),
                ('designer_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disgner_legal', to='professionals.datadesignerlegal')),
                ('director_works_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direktor_individual', to='professionals.datadirectorworksindividual')),
                ('director_works_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direktor_legal', to='professionals.datadirectorworkslegal')),
                ('energy_expert_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividual', to='professionals.dataenergyexpertindividual')),
                ('energy_expert_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_legal', to='professionals.dataenergyexpertlegal')),
                ('resp_work_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposible_for_work_ind', to='professionals.dataresponsibleforworksindividual')),
                ('resp_work_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposible_for_work_leg', to='professionals.dataresponsibleforworkslegal')),
                ('security_exe_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec_exe_individual', to='professionals.datasecuritycoordinatorexecutionindividual')),
                ('security_exe_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec_exe_legal', to='professionals.datasecuritycoordinatorexecutionlegal')),
                ('security_plan_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secutiy_individual', to='professionals.datasecuritycoordinatorindividual')),
                ('security_plan_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_individual', to='professionals.datasecuritycoordinatorlegal')),
                ('thermotechnical_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='professionals.datathermotechnicalindividual')),
                ('thermotechnical_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='professionals.datathermotechnicallegal')),
            ],
        ),
    ]
