# Generated by Django 3.2.6 on 2021-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadesignerindividual',
            name='security_case_technician',
            field=models.CharField(choices=[('4%', '4%'), ('4%', '5%')], max_length=5),
        ),
        migrations.AlterField(
            model_name='datadirectorworksindividual',
            name='security_case_technician',
            field=models.CharField(choices=[('4%', '4%'), ('4%', '5%')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertindividual',
            name='security_case_technician',
            field=models.CharField(choices=[('4%', '4%'), ('4%', '5%')], max_length=5),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworksindividual',
            name='security_case_technician',
            field=models.CharField(choices=[('4%', '4%'), ('4%', '5%')], max_length=5),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionindividual',
            name='security_case_technician',
            field=models.CharField(choices=[('4%', '4%'), ('4%', '5%')], max_length=5),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorindividual',
            name='security_case_technician',
            field=models.CharField(choices=[('4%', '4%'), ('4%', '5%')], max_length=5),
        ),
        migrations.AlterField(
            model_name='datathermotechnicalindividual',
            name='security_case_technician',
            field=models.CharField(choices=[('4%', '4%'), ('4%', '5%')], max_length=5),
        ),
    ]
