# Generated by Django 3.2.6 on 2021-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadesignerindividual',
            name='fiscal_code',
            field=models.IntegerField(),
        ),
    ]
