# Generated by Django 3.2.6 on 2021-11-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_table',
            name='designer_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disgner_individual', to='professionals.datadesignerindividual'),
        ),
    ]
