# Generated by Django 3.2.6 on 2021-12-30 13:38

import apps.professionals.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadesignerindividual',
            name='activity_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datadesignerindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datadesignerindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datadesignerlegal',
            name='cap_reg_office',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datadesignerlegal',
            name='rep_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datadirectorworksindividual',
            name='activity_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datadirectorworksindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datadirectorworksindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datadirectorworkslegal',
            name='cap_reg_office',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datadirectorworkslegal',
            name='rep_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertindividual',
            name='activity_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertlegal',
            name='cap_reg_office',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='dataenergyexpertlegal',
            name='rep_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworksindividual',
            name='activity_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworksindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworksindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworkslegal',
            name='cap_reg_office',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='dataresponsibleforworkslegal',
            name='rep_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionindividual',
            name='activity_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionlegal',
            name='cap_reg_office',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorexecutionlegal',
            name='rep_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorindividual',
            name='activity_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorlegal',
            name='cap_reg_office',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datasecuritycoordinatorlegal',
            name='rep_dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datathermotechnicalindividual',
            name='activity_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datathermotechnicalindividual',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='datathermotechnicalindividual',
            name='residence_cap',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datathermotechnicallegal',
            name='cap_reg_office',
            field=models.CharField(max_length=5, validators=[apps.professionals.models.validate_cap]),
        ),
        migrations.AlterField(
            model_name='datathermotechnicallegal',
            name='rep_dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
