# Generated by Django 3.2.6 on 2021-11-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211101_0915'),
        ('professionals', '0002_alter_datadesignerindividual_fiscal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadesignerindividual',
            name='form_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.formfaccata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datadesignerlegal',
            name='form_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.formfaccata'),
            preserve_default=False,
        ),
    ]
