# Generated by Django 3.2.6 on 2021-11-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_prof_table_designer_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_table',
            name='designer_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disgner_legal', to='professionals.datadesignerlegal'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='director_works_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direktor_individual', to='professionals.datadirectorworksindividual'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='director_works_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direktor_legal', to='professionals.datadirectorworkslegal'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='energy_expert_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividual', to='professionals.dataenergyexpertindividual'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='energy_expert_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_legal', to='professionals.dataenergyexpertlegal'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='resp_work_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposible_for_work_ind', to='professionals.dataresponsibleforworksindividual'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='resp_work_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposible_for_work_leg', to='professionals.dataresponsibleforworkslegal'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='security_exe_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_exe_individual', to='professionals.datasecuritycoordinatorexecutionindividual'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='security_exe_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_exe_legal', to='professionals.datasecuritycoordinatorexecutionlegal'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='security_plan_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secutiy_individual', to='professionals.datasecuritycoordinatorindividual'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='security_plan_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_individual', to='professionals.datasecuritycoordinatorlegal'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='thermotechnical_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='professionals.datathermotechnicalindividual'),
        ),
        migrations.AlterField(
            model_name='prof_table',
            name='thermotechnical_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='professionals.datathermotechnicallegal'),
        ),
    ]
