# Generated by Django 3.2.6 on 2021-11-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_auto_20211112_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prof_table',
            options={'verbose_name': 'Proifessionals Table List'},
        ),
    ]
