# Generated by Django 3.2.6 on 2021-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_auto_20211108_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadesignerindividual',
            old_name='province_college_registration_order',
            new_name='number_description',
        ),
        migrations.RenameField(
            model_name='datadesignerlegal',
            old_name='company_registration_number',
            new_name='number_of_inscription_enterprises_register',
        ),
        migrations.RenameField(
            model_name='datadesignerlegal',
            old_name='province_of_registration',
            new_name='province_of_inscription_enterprises_register',
        ),
        migrations.RenameField(
            model_name='datadesignerlegal',
            old_name='rep_tax_code',
            new_name='rep_fiscal_code',
        ),
        migrations.AddField(
            model_name='datadesignerlegal',
            name='rep_residence_municipality',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
