# Generated by Django 3.2.6 on 2021-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='street',
            field=models.CharField(blank=True, default=0, max_length=150, null=True, verbose_name="VIA E NUMERO IN CUI SI TROVA L'IMMOBILE"),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='thousands_benef_diss',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='MILLESIMI DI BENEFICIO DELLO SCONTO IN FATTURA SU PARTI COMUNI'),
        ),
    ]
