# Generated by Django 3.2.6 on 2021-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_formfaccata_beneficiary'),
        ('beneficary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='select_form',
            field=models.ManyToManyField(to='app.FormFaccata'),
        ),
    ]
