# Generated by Django 3.2.6 on 2022-04-07 13:46

import apps.beneficary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='legal_tax_code_rep',
            field=models.CharField(blank=True, max_length=16, validators=[apps.beneficary.models.validate_fiscal_code], verbose_name="CODICE FISCALE LEGALE RAPPRESENTATE SOCIETA' BENEFICIARIA o del BENEFICIARIO PERSONA FISICA"),
        ),
    ]
