# Generated by Django 3.2.6 on 2021-12-30 13:41

import apps.beneficary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='cap_of_residance_rep',
            field=models.CharField(max_length=5, validators=[apps.beneficary.models.validate_cap], verbose_name="CAP RESIDENZA LEGALE RAPPRESENTATE SOCIETA' BENEFICIARIA o del BENEFICIARIO PERSONA FISICA"),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='dob_of_rep',
            field=models.DateField(default=datetime.date.today, verbose_name="DATA NASCITA LEGALE RAPPRESENTATE SOCIETA' BENEFICIARIA o del BENEFICIARIO PERSONA FISICA"),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='post_code_cap',
            field=models.CharField(max_length=5, validators=[apps.beneficary.models.validate_cap], verbose_name="CAP SEDE LEGALE SOCIETA' BENEFICIARIA"),
        ),
    ]
