# Generated by Django 3.2.6 on 2022-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0002_auto_20211230_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='single_ownership_fee',
            field=models.CharField(choices=[('1', '1'), ('1/2', '1/2'), ('1/3', '1/3'), ('1/4', '1/4'), ('1/5', '1/5'), ('1/6', '1/6'), ('1/7', '1/7'), ('1/8', '1/8')], max_length=50, verbose_name="QUOTA PROPRIETA' DEL SINGOLO"),
        ),
    ]
