# Generated by Django 3.2.6 on 2021-11-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0002_beneficiary_select_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='amount_advance_deposit_by_customer_common',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='IMPORTO ACCONTO INTERVENTI COMUNI - CASSA PREVIDENZA INCLUSA E IVA INCLUSA'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='amount_discount_common',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='IMPORTO SCONTO IN FATTURA INTERVENTI COMUNI - CASSA PREVIDENZA INCLUSA E IVA INCLUSA'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='amount_discount_subjective',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='IMPORTO SCONTO IN FATTURA INTERVENTI SOGGETTIVI - CASSA PREVIDENZA INCLUSA E IVA INCLUSA'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='thousands_benef_diss',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='MILLESIMI DI BENEFICIO DELLO SCONTO IN FATTURA SU PARTI COMUNI'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='total_discount',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='IMPORTO COMPLESSIVO SCONTO IN FATTURA - CASSA PREVIDENZA INCLUSA E IVA INCLUSA'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='total_thousands',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='MILLESIMI COMPLESSIVI'),
        ),
    ]
