# Generated by Django 3.2.6 on 2021-11-22 13:54

from django.db import migrations
import internationalflavor.vat_number.models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0002_auto_20211112_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='vat_number_company',
            field=internationalflavor.vat_number.models.VATNumberField(blank=True, countries=['IT'], verbose_name='IVA-C.F'),
        ),
    ]
