# Generated by Django 3.2.6 on 2021-11-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0003_auto_20211105_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='province_reg_comp_office',
            field=models.CharField(blank=True, max_length=20, verbose_name="PROVINCIA ISCRIZIONE REGISTRO IMPRESE SOCIETA' BENEFICIARIA"),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='province_reg_office',
            field=models.CharField(blank=True, max_length=20, verbose_name="PROVINCIA  SEDE LEGALE SOCIETA' BENEFICIARIA"),
        ),
    ]
