# Generated by Django 3.2.6 on 2021-11-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficary', '0004_auto_20211105_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='cap_of_residance_rep',
            field=models.CharField(blank=True, max_length=50, verbose_name="CAP RESIDENZA LEGALE RAPPRESENTATE SOCIETA' BENEFICIARIA o del BENEFICIARIO PERSONA FISICA"),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='total_adv_deposit_customer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='IMPORTO COMPLESSIVO ACCONTO - CASSA PREVIDENZA INCLUSA E IVA INCLUSA'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='IMPORTO COMPLESSIVO SCONTO IN FATTURA - CASSA PREVIDENZA INCLUSA E IVA INCLUSA'),
        ),
    ]
