# Generated by Django 3.2.6 on 2021-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverallInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount_of_work', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
