# Generated by Django 3.2.6 on 2021-10-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallinventory',
            name='x',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='overallinventory',
            name='y',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
