# Generated by Django 3.2.6 on 2021-10-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20211020_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallinventory',
            name='z',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
