# Generated by Django 3.2.6 on 2021-10-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_overallinventory_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallinventory',
            name='z',
            field=models.IntegerField(default=1, max_length=1, null=True),
        ),
    ]
