# Generated by Django 3.2.6 on 2021-10-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20211021_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonworkexvat',
            name='discount_in_invoice',
            field=models.DecimalField(choices=[(0.9, '90%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='ss_cash_for_tech_exp',
            field=models.DecimalField(choices=[(0, '(0%'), (0.04, '(4%'), (0.05, '(5%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_total_work',
            field=models.DecimalField(choices=[(0.1, '10%'), (0.22, '22%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='discount_in_invoice',
            field=models.DecimalField(choices=[(0.9, '90%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='ss_cash_for_tech_exp',
            field=models.DecimalField(choices=[(0, '(0%'), (0.04, '(4%'), (0.05, '(5%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_total_work',
            field=models.DecimalField(choices=[(0.1, '10%'), (0.22, '22%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='discount_in_invoice',
            field=models.DecimalField(choices=[(0.9, '90%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_tech_exp',
            field=models.DecimalField(choices=[(0, '(0%'), (0.04, '(4%'), (0.05, '(5%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_total_work',
            field=models.DecimalField(choices=[(0.1, '10%'), (0.22, '22%')], decimal_places=2, max_digits=4),
        ),
    ]
