# Generated by Django 3.2.6 on 2021-10-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20211022_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonworktaxable',
            name='total_amt_of_work',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overalltaxable',
            name='total_amt_of_work',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworktaxable',
            name='total_amt_of_work',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
