# Generated by Django 3.2.6 on 2021-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_auto_20211022_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonworkexvat',
            name='ss_cash_for_tech_exp',
            field=models.DecimalField(choices=[(0, '0%'), (0.04, '4%'), (0.05, '5%')], decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_of_the_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_of_the_order_amount_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='ss_cash_for_tech_exp',
            field=models.DecimalField(choices=[(0, '0%'), (0.04, '4%'), (0.05, '5%')], decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_of_the_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_of_the_order_amount_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_tech_exp',
            field=models.DecimalField(choices=[(0, '0%'), (0.04, '4%'), (0.05, '5%')], decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_of_the_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_of_the_order_amount_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
