# Generated by Django 3.2.6 on 2021-10-26 08:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20211022_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonworkexvat',
            name='ss_cash_for_tech_exp',
        ),
        migrations.RemoveField(
            model_name='overallexvat',
            name='ss_cash_for_tech_exp',
        ),
        migrations.RemoveField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_tech_exp',
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='ss_cash_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='ss_cash_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='ss_cash_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='ss_cash_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='ss_cash_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='ss_cash_for_tech_exp_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='ss_cash_for_tech_exp_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='vat_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='vat_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='vat_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='vat_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='vat_for_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='vat_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commonworkexvat',
            name='vat_for_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='ss_cash_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='ss_cash_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='ss_cash_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='ss_cash_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='ss_cash_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='ss_cash_for_tech_exp_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='ss_cash_for_tech_exp_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='vat_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='vat_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='vat_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='vat_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='vat_for_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='vat_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='overallexvat',
            name='vat_for_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_tech_exp_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='ss_cash_for_tech_exp_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.04'), '4%'), (Decimal('0.05'), '5%')], decimal_places=2, default=Decimal('0.04'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='vat_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='vat_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='vat_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='vat_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='vat_for_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='vat_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectiveworkexvat',
            name='vat_for_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='discount_in_invoice',
            field=models.DecimalField(choices=[(Decimal('0.9'), '90%')], decimal_places=2, default=Decimal('0.9'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='total_of_the_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='total_tech_exp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_total_work',
            field=models.DecimalField(choices=[(Decimal('0.1'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.1'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='discount_in_invoice',
            field=models.DecimalField(choices=[(Decimal('0.9'), '90%')], decimal_places=2, default=Decimal('0.9'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='total_of_the_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='total_tech_exp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_total_work',
            field=models.DecimalField(choices=[(Decimal('0.1'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.1'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='discount_in_invoice',
            field=models.DecimalField(choices=[(Decimal('0.9'), '90%')], decimal_places=2, default=Decimal('0.9'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='total_of_the_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='total_tech_exp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_total_work',
            field=models.DecimalField(choices=[(Decimal('0.1'), '10%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.1'), max_digits=10),
        ),
    ]
