# Generated by Django 3.2.6 on 2021-10-26 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_auto_20211026_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonworkexvat',
            old_name='ss_cash_for_tech_exp_energy_expert',
            new_name='ss_cash_for_energy_expert',
        ),
        migrations.RenameField(
            model_name='commonworkexvat',
            old_name='ss_cash_for_tech_exp_thermotechnical',
            new_name='ss_cash_for_thermotechnical',
        ),
        migrations.RenameField(
            model_name='overallexvat',
            old_name='ss_cash_for_tech_exp_energy_expert',
            new_name='ss_cash_for_energy_expert',
        ),
        migrations.RenameField(
            model_name='overallexvat',
            old_name='ss_cash_for_tech_exp_thermotechnical',
            new_name='ss_cash_for_thermotechnical',
        ),
        migrations.RenameField(
            model_name='subjectiveworkexvat',
            old_name='ss_cash_for_tech_exp_energy_expert',
            new_name='ss_cash_for_energy_expert',
        ),
        migrations.RenameField(
            model_name='subjectiveworkexvat',
            old_name='ss_cash_for_tech_exp_thermotechnical',
            new_name='ss_cash_for_thermotechnical',
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkexvat',
            name='vat_for_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='vat_for_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_coordinator_safety_des',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_coordinator_safety_exe',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_designer',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_director_of_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_energy_expert',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_respo_work',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='vat_for_thermotechnical',
            field=models.DecimalField(choices=[(Decimal('0'), '0%'), (Decimal('0.22'), '22%')], decimal_places=2, default=Decimal('0.22'), max_digits=10),
        ),
    ]
