# Generated by Django 3.2.6 on 2021-10-27 08:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_auto_20211026_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonworkexvat',
            name='discount_in_invoice',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.9'), '90%')], decimal_places=2, default=Decimal('0.9'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='poss_respo_work',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='tech_exp_coordinator_safety_des',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='tech_exp_coordinator_safety_exe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='tech_exp_designer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='tech_exp_director_of_work',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='tech_exp_energy_expert',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='tech_exp_thermotechnical',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_amt_of_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_amt_of_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_amt_safety_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_amt_safety_charges_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_of_the_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_of_the_order_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_tech_exp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='total_tech_exp_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commonworkincvat',
            name='vat_for_total_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='overallexvat',
            name='discount_in_invoice',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.9'), '90%')], decimal_places=2, default=Decimal('0.9'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='poss_respo_work',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='tech_exp_coordinator_safety_des',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='tech_exp_coordinator_safety_exe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='tech_exp_designer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='tech_exp_director_of_work',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='tech_exp_energy_expert',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='tech_exp_thermotechnical',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_amt_of_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_amt_of_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_amt_safety_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_amt_safety_charges_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_of_the_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_of_the_order_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_tech_exp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='total_tech_exp_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='vat_for_total_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkexvat',
            name='discount_in_invoice',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.9'), '90%')], decimal_places=2, default=Decimal('0.9'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='poss_respo_work',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='tech_exp_coordinator_safety_des',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='tech_exp_coordinator_safety_exe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='tech_exp_designer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='tech_exp_director_of_work',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='tech_exp_energy_expert',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='tech_exp_thermotechnical',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_amt_of_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_amt_of_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_amt_safety_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_amt_safety_charges_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_of_the_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_of_the_order_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_tech_exp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='total_tech_exp_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='vat_for_total_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
