# Generated by Django 3.2.6 on 2021-10-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_auto_20211027_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonworkincvat',
            name='vat_for_total_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallincvat',
            name='vat_for_total_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkincvat',
            name='vat_for_total_work',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
