# Generated by Django 3.2.6 on 2021-10-27 09:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_auto_20211027_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonworkincvat',
            name='poss_respo_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commonworkincvat',
            name='tech_exp_coordinator_safety_des_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commonworkincvat',
            name='tech_exp_coordinator_safety_exe_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commonworkincvat',
            name='tech_exp_designer_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commonworkincvat',
            name='tech_exp_director_of_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commonworkincvat',
            name='tech_exp_energy_expert_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commonworkincvat',
            name='tech_exp_thermotechnical_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overallincvat',
            name='poss_respo_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overallincvat',
            name='tech_exp_coordinator_safety_des_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overallincvat',
            name='tech_exp_coordinator_safety_exe_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overallincvat',
            name='tech_exp_designer_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overallincvat',
            name='tech_exp_director_of_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overallincvat',
            name='tech_exp_energy_expert_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='overallincvat',
            name='tech_exp_thermotechnical_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subjectiveworkincvat',
            name='poss_respo_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subjectiveworkincvat',
            name='tech_exp_coordinator_safety_des_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subjectiveworkincvat',
            name='tech_exp_coordinator_safety_exe_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subjectiveworkincvat',
            name='tech_exp_designer_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subjectiveworkincvat',
            name='tech_exp_director_of_work_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subjectiveworkincvat',
            name='tech_exp_energy_expert_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subjectiveworkincvat',
            name='tech_exp_thermotechnical_amount_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
    ]
