# Generated by Django 3.2.6 on 2021-10-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_auto_20211027_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('common_ex_vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.commonworkexvat')),
                ('common_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.commonworkreport')),
                ('overall_ex_vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.overallexvat')),
                ('overall_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.overallreport')),
                ('subjective_ex_vat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.subjectiveworkexvat')),
                ('subjective_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.subjectiveworkreport')),
            ],
        ),
    ]
