# Generated by Django 3.2.6 on 2021-10-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_tablecontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecontract',
            name='common_in_vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.commonworkincvat'),
        ),
        migrations.AddField(
            model_name='tablecontract',
            name='common_taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.commonworktaxable'),
        ),
        migrations.AddField(
            model_name='tablecontract',
            name='overall_in_vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.overallincvat'),
        ),
        migrations.AddField(
            model_name='tablecontract',
            name='overall_taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.overalltaxable'),
        ),
        migrations.AddField(
            model_name='tablecontract',
            name='subjective_in_vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.subjectiveworkincvat'),
        ),
        migrations.AddField(
            model_name='tablecontract',
            name='subjective_taxable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.subjectiveworktaxable'),
        ),
    ]
