# Generated by Django 3.2.6 on 2021-10-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_auto_20211027_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonworkexvat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='commonworkincvat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='commonworkreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='commonworktaxable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='overallexvat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='overallincvat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='overallreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='overalltaxable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subjectiveworkexvat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subjectiveworkincvat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subjectiveworkreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subjectiveworktaxable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tablecontract',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='commonworkreport',
            name='total_amount_includin_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='overallreport',
            name='total_amount_includin_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='subjectiveworkreport',
            name='total_amount_includin_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
