# Generated by Django 3.2.6 on 2021-09-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('check_me_out', models.BooleanField(default=False)),
                ('text', models.EmailField(max_length=54)),
                ('example_select', models.IntegerField()),
                ('text_area', models.EmailField(max_length=254)),
            ],
        ),
    ]
