# Generated by Django 3.2.6 on 2021-10-14 11:10

from django.db import migrations, models
import django.utils.timezone
import internationalflavor.vat_number.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationindividual',
            name='activity_location_cap',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='activity_municipality',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='activity_province',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='activity_street',
            field=models.CharField(default='Street', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='activity_street_number',
            field=models.CharField(default=22, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='birthplace',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='birthplace_county',
            field=models.CharField(default='tor', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='first_name',
            field=models.CharField(default='Kyle', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='fiscal_code',
            field=models.CharField(default='10212', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='last_name',
            field=models.CharField(default='Test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='residence_city',
            field=models.CharField(default='Turino', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='residence_province',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='residence_street',
            field=models.CharField(default='TT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='residence_street_number',
            field=models.CharField(default=22, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrationindividual',
            name='vat_number',
            field=internationalflavor.vat_number.models.VATNumberField(countries=['IT'], default=2121212),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominiumdata',
            name='select_administrator',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Individual ', 'Individual')], max_length=11, null=True),
        ),
    ]
