# Generated by Django 3.2.6 on 2021-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211014_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumdata',
            name='select_administrator',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Individual', 'Individual')], max_length=10, null=True),
        ),
    ]
