# Generated by Django 3.2.6 on 2021-10-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_condominiumdata_select_administrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrationindividual',
            old_name='title_of_admin',
            new_name='title',
        ),
    ]
