# Generated by Django 3.2.6 on 2021-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_title_of_admin_administrationindividual_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumdata',
            name='cap',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
